### ISSUE TITLE
Theresa Windus Profile

### ISSUE THREAD

**Issue by ryanmrichard** [SIMCODES-ISU/SIMCODES-ISU.github.io#10]
Please add your mentor profile to the SIMCODES website. This requires the following steps:

- [x] Please add yourself as a website author [here](https://github.com/SIMCODES-ISU/SIMCODES-ISU.github.io/blob/main/docs/_data/authors.yaml).
- [x] Please create your profile page. See [Ryan's](https://github.com/SIMCODES-ISU/SIMCODES-ISU.github.io/blob/main/docs/_mentors/ryan_richard.md) for an example. 
- [x] Please open a pull request to push these changes to the main branch.

**Comment by twindus** [comment]
The profile is in review status, so closing.
